---
- name: install packages
  yum:
      name: "{{ item }}"
      state: latest
      update_cache: true
  items:
      - php-fpm
      - php-pgsql
      - php-gd
      - php-zip

- name: change listen
  replace:
      path: /etc/php-fpm.d/www.conf
      regexp: '^listen.+$'
      replace: 'listen = 0.0.0.0:9001'

- name: change listen.allowed_clients
  replace:
      path: /etc/php-fpm.d/www.conf
      regexp: '^listen\.allowed_clients.+$'
      replace: 'listen.allowed_clients = 127.0.0.1,172.18.0.2,172.18.0.3'
