---
- name: create /usr/share/nginx/www-master
  file:
      path: /usr/share/nginx/www-master
      owner: root
      group: root
      state: directory

- name: setup website
  template:
      src: settings.php.j2
      dest: /usr/share/nginx/www-master/settings.php
      owner: root
      group: root
      mode: 0444

