---
- name: create /usr/share/nginx
  file:
      path: /usr/share/nginx/
      owner: root
      group: root
      state: directory

- name: install unzip
  apt:
      name: unzip
      update_cache: yes
      state: latest

- name: install rml website
  get_url:
      url: https://github.com/RadicalMilitantLibrary/www/archive/master.zip
      dest: /tmp/master.zip
      validate_certs: no

- name: entpacke website
  unarchive:
      remote_src: yes
      src:  /tmp/master.zip
      dest: /usr/share/nginx

- name: deinstall unzip
  apt:
      name: unzip
      state: absent

- name: remove file
  file:
      path: /tmp/master.zip
      state: absent

- name: set file perms
  file:
      path: /usr/share/nginx/
      owner: root
      group: root
      state: directory
