---
postgres_password: ""
webuser_password: foobarbuzmussanderssein


DB_SERVER: 172.18.0.1
DB_PASS: "{{ webuser_password }}"
SECRET_SALT: ""

php_major_version: 5
php_minor_version: 5
#ansible_python_interpreter: "/usr/bin/env python"
