---
 - hosts: localhost
   become: true
   tasks:
    - name: create /rml
      file:
        path: /rml
        owner: root
        group: root
        state: directory

    - name: install packages
      yum:
        name: "{{ item }}"
        update_cache: yes
        state: latest
      with_items:
        - unzip
        - rsync
      tags:
        - synchronize

# Website install
    - name: sleep for 60s and continue with play
      wait_for:
        host: github.com
        port: 80
        timeout: 60

    - name: download rml website
      git:
        repo: https://github.com/RadicalMilitantLibrary/www.git
        dest: /rml/www-master
# Website install end
# Website update
    - name: download rml database
      git:
        repo: https://github.com/RadicalMilitantLibrary/database.git
        dest: /rml/database-master

    - name: synchronize website authors
      synchronize:
        dest: /rml/www-master/authors/
        src: /rml/database-master/1077.authors/
        partial: yes
      delegate_to: localhost
      tags:
        - synchronize

    - name: synchronize website covers
      synchronize:
        dest: /rml/www-master/covers/
        src: /rml/database-master/1077.covers/
        partial: yes
      delegate_to: localhost
      tags:
        - synchronize

    - name: synchronize website pictures
      synchronize:
        dest: /rml/www-master/pictures/
        src: /rml/database-master/1077.pictures/
        partial: yes
      delegate_to: localhost
      tags:
        - synchronize

    - name: remove file
      file:
        path: /tmp/master.zip
        state: absent
# Website update end

    - name: deinstall packages
      yum:
        name: "{{ item }}"
        state: absent
      with_items:
        - unzip
        - rsync
      tags:
        - synchronize

